# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               shemerey.com
tagline:             'My Blog about tech, Web & Mobile development. IoT etc.'
description:         ''
url:                 http://shemerey.com
baseurl:             ''
paginate:            5

gems: [jekyll-paginate]

graphviz:
  options: "-Tsvg" # 'dot' command option

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
